"""Creative building blocks used to seed project ideation (domains, archetypes, twists)."""

from __future__ import annotations

# (name, keywords used to detect saturation in existing repos, niche angles, weight)
DOMAINS: list[dict] = [
    {"name": "developer tooling", "kw": ["cli", "dev", "lint", "git"], "weight": 1.0,
     "angles": ["commit archaeology and code-ownership insight", "local-first log/trace explorer",
                "monorepo impact analysis", "flaky-test hunting", "dependency license auditing"]},
    {"name": "observability & SRE", "kw": ["metric", "monitor", "trace", "alert"], "weight": 1.0,
     "angles": ["SLO burn-rate calculator", "incident timeline reconstruction",
                "cron/job drift detector", "synthetic uptime probes from a single binary"]},
    {"name": "security & privacy", "kw": ["secret", "security", "privacy", "vuln"], "weight": 1.0,
     "angles": ["SBOM diffing between releases", "exposed-config scanner for IaC",
                "personal data-broker opt-out tracker", "GitHub Actions permission auditor"]},
    {"name": "AI/LLM engineering", "kw": ["llm", "prompt", "agent", "rag", "ai"], "weight": 1.2,
     "angles": ["prompt regression test harness", "LLM cost/latency benchmark runner",
                "MCP server for a niche data source", "eval dataset builder from real logs",
                "guardrail/PII redaction proxy"]},
    {"name": "data engineering", "kw": ["etl", "pipeline", "dataset", "csv", "parquet"], "weight": 1.0,
     "angles": ["schema drift detector for CSV/JSON feeds", "tiny columnar data-diff tool",
                "open-data harmonizer for Brazilian government datasets"]},
    {"name": "education & learning", "kw": ["learn", "study", "quiz", "course"], "weight": 1.0,
     "angles": ["spaced-repetition for code snippets", "adaptive exercise generator for SQL",
                "reading-list scheduler with progress analytics"]},
    {"name": "health & wellbeing", "kw": ["health", "fitness", "sleep", "habit"], "weight": 0.8,
     "angles": ["sleep-debt estimator from wearable exports", "medication reminder with interaction notes",
                "ergonomics/break coach for developers"]},
    {"name": "civic tech & Brazil", "kw": ["gov", "civic", "sus", "cep", "ibge"], "weight": 1.3,
     "angles": ["public-transparency portal scraper with alerts", "electoral/legislative tracker",
                "CEP/IBGE/ANATEL open-data toolkit", "Brazilian holiday & business-day engine"]},
    {"name": "creative & media", "kw": ["music", "video", "image", "audio", "art"], "weight": 1.0,
     "angles": ["generative palette/typography tool", "podcast chapter & show-notes generator",
                "procedural pixel-art sprite studio", "subtitle sync/fix toolkit"]},
    {"name": "games & play", "kw": ["game", "rpg", "puzzle", "play"], "weight": 1.0,
     "angles": ["tabletop RPG campaign manager", "terminal roguelike with daily seeds",
                "puzzle generator with solver and difficulty rating"]},
    {"name": "home, maker & IoT", "kw": ["iot", "sensor", "home", "arduino", "mqtt"], "weight": 1.0,
     "angles": ["MQTT message recorder/replayer", "energy-usage forecaster from smart-meter data",
                "plant-care scheduler driven by sensor feeds"]},
    {"name": "productivity & knowledge", "kw": ["note", "task", "wiki", "pkm", "calendar"], "weight": 0.9,
     "angles": ["meeting-notes to action-items extractor", "personal knowledge graph from markdown",
                "time-blocking planner that reads calendar exports"]},
    {"name": "travel, food & local life", "kw": ["travel", "recipe", "food", "trip"], "weight": 1.0,
     "angles": ["recipe scaler with pantry substitution engine", "trip-itinerary conflict checker",
                "restaurant-bill splitter with tip/tax rules"]},
    {"name": "science & numeric computing", "kw": ["science", "physics", "stat", "simulation"], "weight": 1.0,
     "angles": ["Monte Carlo simulation playground", "unit-aware calculator DSL",
                "A/B-test sample-size and significance toolkit"]},
    {"name": "accessibility & i18n", "kw": ["a11y", "i18n", "translate", "locale"], "weight": 1.0,
     "angles": ["WCAG contrast/audit CLI for design tokens", "translation-memory diff tool",
                "pt-BR plain-language rewriter checker"]},
    {"name": "open-source maintenance", "kw": ["release", "changelog", "maintainer", "triage"], "weight": 1.1,
     "angles": ["issue triage scorer", "release-notes composer from PR labels",
                "contributor-onboarding health checker"]},
    {"name": "small-business & freelancing", "kw": ["invoice", "freelanc", "mei", "crm"], "weight": 0.9,
     "angles": ["proposal/scope-creep tracker", "client-retainer burn-down dashboard",
                "NFS-e/boleto reconciliation helper for MEI"]},
    {"name": "finance (niche only)", "kw": ["financ", "expense", "budget", "wallet", "invest"], "weight": 0.25,
     "angles": ["FIFO/average-cost capital-gains calculator for B3 trades",
                "subscription-price-hike detector from bank CSV exports"]},
]

# (name, what it is, suggested stacks)
ARCHETYPES: list[dict] = [
    {"name": "CLI tool", "desc": "single-purpose command-line tool with subcommands, JSON/table output",
     "stacks": ["Go", "Rust", "Python + Typer", "Node.js + TypeScript"]},
    {"name": "reusable library + demo", "desc": "well-typed library with a runnable demo and API docs",
     "stacks": ["Python", "TypeScript", "Go", "Rust"]},
    {"name": "HTTP API service", "desc": "REST/JSON service with OpenAPI spec, persistence and auth",
     "stacks": ["Python + FastAPI", "Go + chi", "Node.js + Fastify"]},
    {"name": "terminal UI app", "desc": "interactive TUI with keyboard navigation",
     "stacks": ["Python + Textual", "Go + Bubble Tea", "Rust + Ratatui"]},
    {"name": "web app (static/PWA)", "desc": "offline-capable single-page app, no backend needed",
     "stacks": ["TypeScript + Vite", "Svelte", "React + Vite"]},
    {"name": "bot / automation", "desc": "event-driven bot for Telegram, Discord or GitHub",
     "stacks": ["Python", "Node.js + TypeScript"]},
    {"name": "GitHub Action / CI tool", "desc": "composite or JS action with fixtures and docs",
     "stacks": ["TypeScript", "Python"]},
    {"name": "MCP server", "desc": "Model Context Protocol server exposing tools/resources for one niche",
     "stacks": ["TypeScript", "Python"]},
    {"name": "data pipeline / analyzer", "desc": "reproducible ingest-transform-report job with sample data",
     "stacks": ["Python + DuckDB", "Go", "Rust + Polars"]},
    {"name": "browser extension", "desc": "MV3 extension with options page and tests",
     "stacks": ["TypeScript + Vite"]},
]

# Constraints that force a distinctive product shape.
TWISTS: list[str] = [
    "must work fully offline with zero external services",
    "must ship with a realistic bundled sample dataset and a one-command demo",
    "must be scriptable: every feature reachable via stable machine-readable output",
    "must include a plugin/extension point with at least two built-in plugins",
    "must explain its results (every output carries the 'why')",
    "must be usable by a non-technical person in under two minutes",
    "must be deterministic and reproducible (seeded, snapshot-tested)",
    "must integrate with a real public API or open dataset (with recorded fixtures for tests)",
]
